name: Deploy VK Mini App
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    env:
      NODE_VERSION: 14.x
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: env MINI_APPS_ACCESS_TOKEN=${{ secrets.SERVICE_TOKEN }} npm run deploy
